#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

# Gradle uchun JDK 17 (Compose Multiplatform 1.10 JVM 11+ talab qiladi)
# Windows: C:\\Users\\Mehrob\\.jdks\\ms-17.0.19
# Linux: /usr/lib/jvm/java-17-openjdk-amd64
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64