server:
  port: 8095

spring:
  application:
    name: geo-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/geo_db}
    username: ${SPRING_DATASOURCE_USERNAME:mexa}
    password: ${SPRING_DATASOURCE_PASSWORD:mexa1234}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:mexa_jwt_2024_secret_key_32chars_long!!}

app:
  internal:
    secret: ${APP_INTERNAL_SECRET:mexa_int_v1_R9x!2Qm#7Lp$4Tw@8Kd%1Nc^6Zh&3By*5Fu(0Ej)9Sa=2Vr+7Hg!4Px#8Lq$6Wt@1}
  realtime:
    enabled: false
    channel: mexa:realtime:events

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
