package mexa.club.authservice.entity;

public enum Permission {
    USER_VIEW, USER_CREATE, USER_EDIT, USER_DELETE, USER_ROLE_ASSIGN,
    PRODUCT_VIEW, PRODUCT_CREATE, PRODUCT_EDIT, PRODUCT_DELETE, PRODUCT_MANAGE,
    ORDER_VIEW, ORDER_CREATE, ORDER_EDIT, ORDER_DELETE, ORDER_MANAGE,
    WAREHOUSE_VIEW, WAREHOUSE_MANAGE, STOCK_VIEW, STOCK_MANAGE,
    AUDIT_LOG_VIEW, AUDIT_LOG_EXPORT,
    PAYMENT_VIEW, PAYMENT_PROCESS, PAYMENT_REFUND, PAYMENT_REPORT,
    DELIVERY_VIEW, DELIVERY_MANAGE, DELIVERY_ASSIGN, DELIVERY_STATUS_UPDATE,
    COURIER_VIEW, COURIER_MANAGE,
    REPORT_VIEW, REPORT_EXPORT, REPORT_FINANCIAL, REPORT_WAREHOUSE,
    ANALYTICS_VIEW, ANALYTICS_EXPORT,
    DISCOUNT_VIEW, DISCOUNT_MANAGE,
    NOTIFICATION_VIEW, NOTIFICATION_MANAGE,
    SYSTEM_CONFIG, ROLE_MANAGE, BACKUP_RESTORE, GEO_MANAGE,
    GROUP_VIEW, GROUP_CREATE, GROUP_EDIT, GROUP_DELETE, GROUP_MANAGE
}
