services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8083}
  geo:
    url: ${GEO_SERVICE_URL:http://localhost:8095}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8087}
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

app:
  internal-secret: ${APP_INTERNAL_SECRET:mexa_int_v1_R9x!2Qm#7Lp$4Tw@8Kd%1Nc^6Zh&3By*5Fu(0Ej)9Sa=2Vr+7Hg!4Px#8Lq$6Wt@1}

scheduler:
  low-stock:
    cron: ${LOW_STOCK_ALERT_CRON:0 0 8 * * *}
