package com.example.mobile_app.util

object Translator {
    private val strings = mapOf(
        // ========== BottomNavBar ==========
        "nav_home" to mapOf(Language.UZ to "Bosh sahifa", Language.RU to "Главная"),
        "nav_categories" to mapOf(Language.UZ to "Katalog", Language.RU to "Каталог"),
        "nav_cart" to mapOf(Language.UZ to "Savat", Language.RU to "Корзина"),
        "nav_orders" to mapOf(Language.UZ to "Buyurtmalar", Language.RU to "Заказы"),
        "nav_profile" to mapOf(Language.UZ to "Profil", Language.RU to "Профиль"),

        // ========== SplashScreen ==========
        "splash_tagline" to mapOf(Language.UZ to "Xarid qilish tajribangizni yuksaltiring", Language.RU to "Улучшите свой опыт покупок"),

        // ========== HomeScreen ==========
        "home_trending" to mapOf(Language.UZ to "Trenddagi mahsulotlar", Language.RU to "Трендовые товары"),
        "home_see_all" to mapOf(Language.UZ to "Barchasini ko'rish", Language.RU to "Смотреть все"),
        "home_recommended" to mapOf(Language.UZ to "Tavsiya etiladi ⭐", Language.RU to "Рекомендуем ⭐"),
        "home_all" to mapOf(Language.UZ to "Barchasi", Language.RU to "Все"),
        "home_logo_m" to mapOf(Language.UZ to "M", Language.RU to "M"),
        "home_delivering_to" to mapOf(Language.UZ to "Yetkazish: ", Language.RU to "Доставка: "),
        "home_delivery_address" to mapOf(Language.UZ to "Navoiy ko'ch, 15", Language.RU to "ул. Навои, 15"),
        "home_flash_sale" to mapOf(Language.UZ to "⚡ FLASH SALE", Language.RU to "⚡ FLASH SALE"),
        "home_flash_discount" to mapOf(Language.UZ to "70% gacha chegirma", Language.RU to "Скидка до 70%"),
        "home_flash_category" to mapOf(Language.UZ to "Elektronika", Language.RU to "Электроника"),
        "home_shop_now" to mapOf(Language.UZ to "Hoziroq xarid qiling", Language.RU to "Купить сейчас"),
        "home_default_brand" to mapOf(Language.UZ to "Mahsulot", Language.RU to "Товар"),
        "home_review_suffix" to mapOf(Language.UZ to " ta baho", Language.RU to " оценки"),

        // ========== CartScreen ==========
        "cart_title" to mapOf(Language.UZ to "Savat", Language.RU to "Корзина"),
        "cart_product_prefix" to mapOf(Language.UZ to "Mahsulot ", Language.RU to "Товар "),
        "cart_unit_price" to mapOf(Language.UZ to " / dona", Language.RU to " / шт"),
        "cart_total_items" to mapOf(Language.UZ to "Jami mahsulotlar:", Language.RU to "Всего товаров:"),
        "cart_quantity_suffix" to mapOf(Language.UZ to " dona", Language.RU to " шт"),
        "cart_type_count" to mapOf(Language.UZ to "Turlar soni:", Language.RU to "Количество видов:"),
        "cart_type_suffix" to mapOf(Language.UZ to " tur", Language.RU to " вида"),
        "cart_place_order" to mapOf(Language.UZ to "Buyurtma berish", Language.RU to "Оформить заказ"),
        "cart_empty_emoji" to mapOf(Language.UZ to "🛒", Language.RU to "🛒"),
        "cart_empty_title" to mapOf(Language.UZ to "Savat bo'sh", Language.RU to "Корзина пуста"),
        "cart_empty_subtitle" to mapOf(Language.UZ to "Mahsulot qo'shing!", Language.RU to "Добавьте товары!"),

        // ========== ProductDetailScreen ==========
        "detail_recommended" to mapOf(Language.UZ to "Tavsiya etiladi", Language.RU to "Рекомендуем"),
        "detail_flash_sale" to mapOf(Language.UZ to "FLASH SALE", Language.RU to "FLASH SALE"),
        "detail_no_price" to mapOf(Language.UZ to "Narx belgilanmagan", Language.RU to "Цена не указана"),
        "detail_low_stock_prefix" to mapOf(Language.UZ to "Faqat ", Language.RU to "Осталось всего "),
        "detail_low_stock_suffix" to mapOf(Language.UZ to " dona qoldi!", Language.RU to " шт!"),
        "detail_material" to mapOf(Language.UZ to "Material: ", Language.RU to "Материал: "),
        "detail_made_in" to mapOf(Language.UZ to "Ishlab chiqarilgan: ", Language.RU to "Произведено: "),
        "detail_color" to mapOf(Language.UZ to "Rang: ", Language.RU to "Цвет: "),
        "detail_other_colors" to mapOf(Language.UZ to "Boshqa ranglar", Language.RU to "Другие цвета"),
        "detail_description" to mapOf(Language.UZ to "Mahsulot tavsifi", Language.RU to "Описание товара"),
        "detail_no_description" to mapOf(Language.UZ to "Mahsulot tavsifi hali qo'shilmagan.", Language.RU to "Описание товара еще не добавлено."),
        "detail_delivery_title" to mapOf(Language.UZ to "Yetkazib berish", Language.RU to "Доставка"),
        "detail_delivery_subtitle" to mapOf(Language.UZ to "2–5 ish kuni ichida", Language.RU to "В течение 2–5 рабочих дней"),
        "detail_delivery_days" to mapOf(Language.UZ to "ish kuni ichida", Language.RU to "рабочих дней"),
        "order_eta_label" to mapOf(Language.UZ to "Taxminiy yetkazish muddati:", Language.RU to "Примерный срок доставки:"),
        "order_eta_days" to mapOf(Language.UZ to "kun ichida", Language.RU to "дней"),
        "detail_return_title" to mapOf(Language.UZ to "Qaytarish", Language.RU to "Возврат"),
        "detail_return_subtitle" to mapOf(Language.UZ to "30 kun ichida bepul", Language.RU to "Бесплатно в течение 30 дней"),
        "detail_warranty_title" to mapOf(Language.UZ to "Kafolat", Language.RU to "Гарантия"),
        "detail_warranty_subtitle" to mapOf(Language.UZ to "1 yil kafolat", Language.RU to "1 год гарантии"),
        "detail_reviews" to mapOf(Language.UZ to "Mijoz sharhlari", Language.RU to "Отзывы клиентов"),
        "detail_view_all" to mapOf(Language.UZ to "Barchasini ko'rish", Language.RU to "Смотреть все"),
        "detail_anonymous" to mapOf(Language.UZ to "Anonim", Language.RU to "Аноним"),
        "detail_total_price" to mapOf(Language.UZ to "Umumiy narx", Language.RU to "Общая цена"),
        "detail_add_to_cart" to mapOf(Language.UZ to "Savatga qo'shish", Language.RU to "Добавить в корзину"),
        "detail_added_to_cart" to mapOf(Language.UZ to "Savatga qo'shildi", Language.RU to "Добавлено в корзину"),
        "detail_char_title" to mapOf(Language.UZ to "Xarakteristikalar", Language.RU to "Характеристики"),
        "detail_char_brand" to mapOf(Language.UZ to "Brend", Language.RU to "Бренд"),
        "detail_char_category" to mapOf(Language.UZ to "Kategoriya", Language.RU to "Категория"),
        "detail_char_barcode" to mapOf(Language.UZ to "Shtrix-kod", Language.RU to "Штрих-код"),
        "detail_char_sku" to mapOf(Language.UZ to "SKU", Language.RU to "Артикул"),
        "detail_char_color" to mapOf(Language.UZ to "Rang", Language.RU to "Цвет"),
        "detail_char_material" to mapOf(Language.UZ to "Material", Language.RU to "Материал"),
        "detail_char_origin" to mapOf(Language.UZ to "Ishlab chiqarilgan", Language.RU to "Произведено в"),
        "detail_char_weight" to mapOf(Language.UZ to "Og'irlik", Language.RU to "Вес"),
        "detail_char_weight_suffix" to mapOf(Language.UZ to " kg", Language.RU to " кг"),
        "detail_char_dimensions" to mapOf(Language.UZ to "O'lchamlar", Language.RU to "Размеры"),
        "detail_char_dimensions_suffix" to mapOf(Language.UZ to "sm", Language.RU to "см"),
        "detail_char_package" to mapOf(Language.UZ to "Qadoqlash", Language.RU to "Упаковка"),
        "detail_char_warranty" to mapOf(Language.UZ to "Kafolat", Language.RU to "Гарантия"),
        "detail_char_warranty_suffix" to mapOf(Language.UZ to " oy", Language.RU to " мес."),
        "detail_char_unit" to mapOf(Language.UZ to "O'lchov birligi", Language.RU to "Ед. измерения"),
        "detail_char_lead_time" to mapOf(Language.UZ to "Yetkazish muddati", Language.RU to "Срок поставки"),
        "detail_char_lead_time_days" to mapOf(Language.UZ to " kun", Language.RU to " дней"),
        "detail_char_status" to mapOf(Language.UZ to "Holat", Language.RU to "Наличие"),
        "detail_char_in_stock" to mapOf(Language.UZ to "Mavjud", Language.RU to "В наличии"),
        "detail_char_out_of_stock" to mapOf(Language.UZ to "Mavjud emas", Language.RU to "Нет в наличии"),
        "detail_review_suffix" to mapOf(Language.UZ to " ta sharh)", Language.RU to " отзывов)"),

        // ========== LoginScreen ==========
        "login_welcome" to mapOf(Language.UZ to "Mexa Marketga xush kelibsiz", Language.RU to "Добро пожаловать в Mexa Market"),
        "login_tagline" to mapOf(Language.UZ to "Xarid qilish tajribangizni yuksaltiring", Language.RU to "Улучшите свой опыт покупок"),
        "login_tab_login" to mapOf(Language.UZ to "Kirish", Language.RU to "Вход"),
        "login_tab_register" to mapOf(Language.UZ to "Ro'yxatdan o'tish", Language.RU to "Регистрация"),
        "login_email_or_username" to mapOf(Language.UZ to "Email yoki foydalanuvchi nomi", Language.RU to "Email или имя пользователя"),
        "login_email_placeholder" to mapOf(Language.UZ to "name@example.com", Language.RU to "name@example.com"),
        "login_password" to mapOf(Language.UZ to "Parol", Language.RU to "Пароль"),
        "login_forgot" to mapOf(Language.UZ to "Parolni unutdim?", Language.RU to "Забыли пароль?"),
        "login_password_placeholder" to mapOf(Language.UZ to "Parolingizni kiriting", Language.RU to "Введите пароль"),
        "login_button" to mapOf(Language.UZ to "Kirish", Language.RU to "Войти"),
        "login_name" to mapOf(Language.UZ to "Ism", Language.RU to "Имя"),
        "login_username_placeholder" to mapOf(Language.UZ to "Foydalanuvchi nomi", Language.RU to "Имя пользователя"),
        "login_email" to mapOf(Language.UZ to "Email", Language.RU to "Email"),
        "login_register_password" to mapOf(Language.UZ to "Parol", Language.RU to "Пароль"),
        "login_password_hint" to mapOf(Language.UZ to "Kamida 8 ta belgi", Language.RU to "Минимум 8 символов"),
        "login_register_button" to mapOf(Language.UZ to "Ro'yxatdan o'tish", Language.RU to "Зарегистрироваться"),
        "login_or" to mapOf(Language.UZ to "  YOKI  ", Language.RU to "  ИЛИ  "),
        "login_google" to mapOf(Language.UZ to "Google orqali kirish", Language.RU to "Войти через Google"),
        "login_terms" to mapOf(Language.UZ to "Davom etish orqali siz Mexa Market Foydalanish Shartlari va Maxfiylik Siyosatiga rozilik bildirasiz.", Language.RU to "Продолжая, вы соглашаетесь с Условиями использования и Политикой конфиденциальности Mexa Market."),

        // ========== CatalogScreen ==========
        "catalog_results" to mapOf(Language.UZ to " natija", Language.RU to " результат"),
        "catalog_loading" to mapOf(Language.UZ to "Yuklanmoqda...", Language.RU to "Загрузка..."),
        "catalog_retry" to mapOf(Language.UZ to "Qayta urinish", Language.RU to "Повторить"),
        "catalog_error" to mapOf(Language.UZ to "Yuklashda xatolik yuz berdi", Language.RU to "Ошибка при загрузке"),
        "catalog_load_more" to mapOf(Language.UZ to "Ko'proq mahsulot", Language.RU to "Больше товаров"),
        "catalog_search_placeholder" to mapOf(Language.UZ to "Mahsulotlar, brendlar qidirish...", Language.RU to "Поиск товаров, брендов..."),
        "catalog_filter" to mapOf(Language.UZ to "Filtrlash", Language.RU to "Фильтр"),
        "catalog_select_category" to mapOf(Language.UZ to "Kategoriyani tanlang", Language.RU to "Выберите категорию"),
        "catalog_select_category_hint" to mapOf(Language.UZ to "Yuqoridagi kategoriyalardan birini bosing", Language.RU to "Нажмите на одну из категорий выше"),
        "cat_electronics" to mapOf(Language.UZ to "Elektronika", Language.RU to "Электроника"),
        "cat_gadgets" to mapOf(Language.UZ to "Gadjetlar", Language.RU to "Гаджеты"),
        "cat_fashion" to mapOf(Language.UZ to "Moda", Language.RU to "Мода"),
        "cat_sports" to mapOf(Language.UZ to "Sport", Language.RU to "Спорт"),
        "cat_cameras" to mapOf(Language.UZ to "Kameralar", Language.RU to "Камеры"),
        "cat_home" to mapOf(Language.UZ to "Uy", Language.RU to "Дом"),
        "cat_beauty" to mapOf(Language.UZ to "Go'zallik", Language.RU to "Красота"),
        "cat_books" to mapOf(Language.UZ to "Kitoblar", Language.RU to "Книги"),
        "cat_toys" to mapOf(Language.UZ to "O'yinchoqlar", Language.RU to "Игрушки"),
        "catalog_promo_title" to mapOf(Language.UZ to "Bahorgi savdo! 🎉", Language.RU to "Весенняя распродажа! 🎉"),
        "catalog_promo_subtitle" to mapOf(Language.UZ to "Barcha elektronikalarda 40% gacha chegirma", Language.RU to "Скидка до 40% на всю электронику"),
        "catalog_title" to mapOf(Language.UZ to "Kategoriyalar", Language.RU to "Категории"),
        "catalog_empty" to mapOf(Language.UZ to "Kategoriyalar topilmadi", Language.RU to "Категории не найдены"),

        // ========== ProfileScreen ==========
        "profile_uz" to mapOf(Language.UZ to "UZ", Language.RU to "UZ"),
        "profile_ru" to mapOf(Language.UZ to "RU", Language.RU to "RU"),
        "profile_en" to mapOf(Language.UZ to "EN", Language.RU to "EN"),
        "profile_logout_title" to mapOf(Language.UZ to "Chiqish", Language.RU to "Выход"),
        "profile_logout_confirm" to mapOf(Language.UZ to "Hisobdan chiqishni xohlaysizmi?", Language.RU to "Вы уверены, что хотите выйти?"),
        "profile_logout_yes" to mapOf(Language.UZ to "Ha, chiqish", Language.RU to "Да, выйти"),
        "profile_cancel" to mapOf(Language.UZ to "Bekor qilish", Language.RU to "Отмена"),
        "profile_default_user" to mapOf(Language.UZ to "Foydalanuvchi", Language.RU to "Пользователь"),
        "profile_edit" to mapOf(Language.UZ to "Profilni tahrirlash", Language.RU to "Редактировать профиль"),
        "profile_addresses" to mapOf(Language.UZ to "Manzillarim", Language.RU to "Мои адреса"),
        "profile_payment" to mapOf(Language.UZ to "To'lov usullari", Language.RU to "Способы оплаты"),
        "profile_favorites" to mapOf(Language.UZ to "Sevimlilar", Language.RU to "Избранное"),
        "profile_settings" to mapOf(Language.UZ to "Sozlamalar", Language.RU to "Настройки"),
        "profile_help" to mapOf(Language.UZ to "Yordam", Language.RU to "Помощь"),
        "profile_logout" to mapOf(Language.UZ to "Chiqish", Language.RU to "Выход"),

        // ========== Umumiy / common ==========
        "common_cancel" to mapOf(Language.UZ to "Bekor qilish", Language.RU to "Отмена"),

        // ========== SearchScreen ==========
        "search_recent_1" to mapOf(Language.UZ to "Simsiz quloqchinlar", Language.RU to "Беспроводные наушники"),
        "search_recent_2" to mapOf(Language.UZ to "Nike krossovkalari", Language.RU to "Кроссовки Nike"),
        "search_recent_3" to mapOf(Language.UZ to "O'yin noutbuki", Language.RU to "Игровой ноутбук"),
        "search_recent_4" to mapOf(Language.UZ to "Aqlli soat", Language.RU to "Умные часы"),
        "search_trending_1" to mapOf(Language.UZ to "Trenddagi noutbuklar", Language.RU to "Трендовые ноутбуки"),
        "search_trending_2" to mapOf(Language.UZ to "Qishki krossovkalar", Language.RU to "Зимние кроссовки"),
        "search_trending_3" to mapOf(Language.UZ to "Mexanik klaviatura", Language.RU to "Механическая клавиатура"),
        "search_trending_4" to mapOf(Language.UZ to "O'yin kursisi", Language.RU to "Игровое кресло"),
        "search_placeholder" to mapOf(Language.UZ to "Mahsulotlarni qidirish...", Language.RU to "Поиск товаров..."),
        "search_voice" to mapOf(Language.UZ to "Ovozli qidiruv", Language.RU to "Голосовой поиск"),
        "search_recent_title" to mapOf(Language.UZ to "So'nggi qidiruvlar", Language.RU to "Недавние поиски"),
        "search_clear_all" to mapOf(Language.UZ to "Barchasini tozalash", Language.RU to "Очистить все"),
        "search_trending_title" to mapOf(Language.UZ to "Trendda hozir", Language.RU to "Сейчас в тренде"),
        "search_categories_title" to mapOf(Language.UZ to "Siz uchun kategoriyalar", Language.RU to "Категории для вас"),
        "search_back" to mapOf(Language.UZ to "Orqaga", Language.RU to "Назад"),
        "search_results" to mapOf(Language.UZ to "Natijalar", Language.RU to "Результаты"),
        "search_no_results_title" to mapOf(Language.UZ to "Hech narsa topilmadi", Language.RU to "Ничего не найдено"),
        "search_no_results_subtitle" to mapOf(Language.UZ to "Boshqa so'rov bilan urinib ko'ring", Language.RU to "Попробуйте другой запрос"),
        "catalog_clear_search" to mapOf(Language.UZ to "Qidiruvni tozalash", Language.RU to "Очистить поиск"),
        "search_loading" to mapOf(Language.UZ to "Qidirilmoqda...", Language.RU to "Поиск..."),
        "search_history_empty" to mapOf(Language.UZ to "Hozircha qidiruvlar yo'q", Language.RU to "Пока нет поисковых запросов"),

        // ========== CheckoutScreen ==========
        "checkout_title" to mapOf(Language.UZ to "Rasmiylashtirish", Language.RU to "Оформление"),
        "checkout_back" to mapOf(Language.UZ to "Orqaga", Language.RU to "Назад"),
        "checkout_place_order" to mapOf(Language.UZ to "Buyurtma berish", Language.RU to "Оформить заказ"),
        "checkout_shipping" to mapOf(Language.UZ to "Yetkazish manzili", Language.RU to "Адрес доставки"),
        "checkout_add_address" to mapOf(Language.UZ to "+ Qo'shish", Language.RU to "+ Добавить"),
        "checkout_address_home" to mapOf(Language.UZ to "Uy", Language.RU to "Дом"),
        "checkout_address_home_line1" to mapOf(Language.UZ to "Navoiy ko'ch, 15", Language.RU to "ул. Навои, 15"),
        "checkout_address_home_line2" to mapOf(Language.UZ to "Toshkent sh, Chilonzor", Language.RU to "г. Ташкент, Чиланзар"),
        "checkout_address_office" to mapOf(Language.UZ to "Ishxona", Language.RU to "Офис"),
        "checkout_address_office_line1" to mapOf(Language.UZ to "Amir Temur ko'ch, 100", Language.RU to "ул. Амира Темура, 100"),
        "checkout_address_office_line2" to mapOf(Language.UZ to "Toshkent sh, Yakkasaroy", Language.RU to "г. Ташкент, Яккасарай"),
        "checkout_payment_method" to mapOf(Language.UZ to "To'lov usuli", Language.RU to "Способ оплаты"),
        "checkout_card" to mapOf(Language.UZ to "Kredit / Debet karta", Language.RU to "Кредитная / Дебетовая карта"),
        "checkout_card_placeholder" to mapOf(Language.UZ to "**** **** **** 4242", Language.RU to "**** **** **** 4242"),
        "checkout_order_summary" to mapOf(Language.UZ to "Buyurtma haqida", Language.RU to "О заказе"),
        "checkout_subtotal" to mapOf(Language.UZ to "Oraliq jami", Language.RU to "Промежуточный итог"),
        "checkout_shipping_fee" to mapOf(Language.UZ to "Yetkazish narxi", Language.RU to "Стоимость доставки"),
        "checkout_free" to mapOf(Language.UZ to "Bepul", Language.RU to "Бесплатно"),
        "checkout_total" to mapOf(Language.UZ to "Umumiy", Language.RU to "Итого"),
        "checkout_edit_address" to mapOf(Language.UZ to "Manzilni tahrirlash", Language.RU to "Редактировать адрес"),
        "checkout_address_hint" to mapOf(Language.UZ to "Manzilni kiriting...", Language.RU to "Введите адрес..."),
        "checkout_items" to mapOf(Language.UZ to "Mahsulotlar", Language.RU to "Товары"),
        "checkout_empty_title" to mapOf(Language.UZ to "Savat bo'sh", Language.RU to "Корзина пуста"),
        "checkout_note_hint" to mapOf(Language.UZ to "Buyurtma izohi (ixtiyoriy)", Language.RU to "Комментарий к заказу (необязательно)"),
        "checkout_discount_code" to mapOf(Language.UZ to "Chegirma kodi", Language.RU to "Промокод"),
        "checkout_discount_code_hint" to mapOf(Language.UZ to "Kodni kiriting", Language.RU to "Введите код"),
        "checkout_address_required" to mapOf(Language.UZ to "Yetkazib berish manzilini kiriting", Language.RU to "Укажите адрес доставки"),
        "checkout_note_title" to mapOf(Language.UZ to "Izoh", Language.RU to "Комментарий"),
        "checkout_service_checking" to mapOf(Language.UZ to "Xizmat hududi tekshirilmoqda...", Language.RU to "Проверка зоны обслуживания..."),
        "checkout_service_ok" to mapOf(Language.UZ to "Bu manzilga yetkazib beramiz ✓", Language.RU to "Доставим по этому адресу ✓"),
        "checkout_service_no" to mapOf(Language.UZ to "Bu manzil xizmat hududidan tashqarida — boshqa manzil tanlang", Language.RU to "Этот адрес вне зоны обслуживания — выберите другой"),
        "order_place_error" to mapOf(Language.UZ to "Buyurtma berishda xatolik", Language.RU to "Ошибка при оформлении заказа"),
        "order_cancel_failed" to mapOf(Language.UZ to "Bekor qilishda xatolik", Language.RU to "Ошибка при отмене заказа"),
        "pay_cash" to mapOf(Language.UZ to "Naqd pul", Language.RU to "Наличные"),
        "pay_card" to mapOf(Language.UZ to "Karta orqali", Language.RU to "Картой"),
        "pay_online" to mapOf(Language.UZ to "Online", Language.RU to "Онлайн"),
        "order_payment_method" to mapOf(Language.UZ to "To'lov usuli:", Language.RU to "Способ оплаты:"),

        // ========== VerifyEmailScreen ==========
        "verify_title" to mapOf(Language.UZ to "Email tasdiqlash", Language.RU to "Подтверждение email"),
        "verify_description" to mapOf(Language.UZ to "Emailingizga 6 xonali kod yuborildi:\n", Language.RU to "На ваш email отправлен 6-значный код:\n"),
        "verify_code_label" to mapOf(Language.UZ to "Tasdiqlash kodi", Language.RU to "Код подтверждения"),
        "verify_code_placeholder" to mapOf(Language.UZ to "123456", Language.RU to "123456"),
        "verify_button" to mapOf(Language.UZ to "Tasdiqlash", Language.RU to "Подтвердить"),
        "verify_resend" to mapOf(Language.UZ to "Kodni qayta yuborish", Language.RU to "Отправить код повторно"),
        "verify_resend_timer_prefix" to mapOf(Language.UZ to "Qayta yuborish (", Language.RU to "Отправить повторно ("),
        "verify_resend_timer_suffix" to mapOf(Language.UZ to " s)", Language.RU to " с)"),

        // ========== OrdersScreen ==========
        "orders_title" to mapOf(Language.UZ to "Buyurtmalarim", Language.RU to "Мои заказы"),
        "orders_default_product" to mapOf(Language.UZ to "Mahsulot", Language.RU to "Товар"),
        "orders_empty_title" to mapOf(Language.UZ to "Buyurtmalar yo'q", Language.RU to "Заказов нет"),
        "orders_empty_subtitle" to mapOf(Language.UZ to "Birinchi buyurtmangizni bering!", Language.RU to "Сделайте свой первый заказ!"),
        "orders_retry" to mapOf(Language.UZ to "Qayta urinish", Language.RU to "Повторить"),
        "order_load_error" to mapOf(Language.UZ to "Buyurtmalarni yuklashda xatolik", Language.RU to "Ошибка загрузки заказов"),
        "orders_status_pending" to mapOf(Language.UZ to "Kutilmoqda", Language.RU to "Ожидается"),
        "orders_status_confirmed" to mapOf(Language.UZ to "Tasdiqlangan", Language.RU to "Подтвержден"),
        "orders_status_processing" to mapOf(Language.UZ to "Jarayonda", Language.RU to "В обработке"),
        "orders_status_shipped" to mapOf(Language.UZ to "Yuborilgan", Language.RU to "Отправлен"),
        "orders_status_delivered" to mapOf(Language.UZ to "Yetkazilgan ✓", Language.RU to "Доставлен ✓"),
        "orders_status_cancelled" to mapOf(Language.UZ to "Bekor qilingan", Language.RU to "Отменен"),
        "orders_number_prefix" to mapOf(Language.UZ to "Buyurtma #", Language.RU to "Заказ #"),
        "orders_total" to mapOf(Language.UZ to "Jami summa:", Language.RU to "Общая сумма:"),
        "orders_products" to mapOf(Language.UZ to "Mahsulotlar:", Language.RU to "Товары:"),
        "orders_date" to mapOf(Language.UZ to "Sana: ", Language.RU to "Дата: "),
        "orders_review" to mapOf(Language.UZ to "  Baho bering", Language.RU to "  Оценить"),
        "orders_cancel" to mapOf(Language.UZ to "Bekor qilish", Language.RU to "Отменить"),
        "orders_items_count_suffix" to mapOf(Language.UZ to " dona", Language.RU to " шт."),
        "order_detail_title" to mapOf(Language.UZ to "Buyurtma tafsilotlari", Language.RU to "Детали заказа"),
        "order_detail_items" to mapOf(Language.UZ to "Mahsulotlar", Language.RU to "Товары"),
        "order_detail_delivery_address" to mapOf(Language.UZ to "Yetkazish manzili: ", Language.RU to "Адрес доставки: "),
        "order_detail_cancel_reason" to mapOf(Language.UZ to "Bekor qilish sababi: ", Language.RU to "Причина отмены: "),
        "order_detail_payment_status" to mapOf(Language.UZ to "To'lov holati:", Language.RU to "Статус оплаты:"),
        "order_payment_unpaid" to mapOf(Language.UZ to " To'lanmagan", Language.RU to " Не оплачен"),
        "order_payment_paid" to mapOf(Language.UZ to " To'langan", Language.RU to " Оплачен"),
        "order_payment_refunded" to mapOf(Language.UZ to " Qaytarilgan", Language.RU to " Возвращен"),

        // ========== WishlistScreen ==========
        "wishlist_title" to mapOf(Language.UZ to "Sevimlilar", Language.RU to "Избранное"),
        "wishlist_empty_title" to mapOf(Language.UZ to "Sevimlilar bo'sh", Language.RU to "Избранное пусто"),
        "wishlist_empty_subtitle" to mapOf(Language.UZ to "Mahsulotlarni yoqtirib qo'ying!", Language.RU to "Добавьте товары в избранное!"),
        "wishlist_product_id" to mapOf(Language.UZ to "Mahsulot ID:", Language.RU to "ID товара:"),
        "wishlist_added" to mapOf(Language.UZ to "Qo'shilgan: ", Language.RU to "Добавлено: "),

        // ========== Home Flash Sale / ratings ==========
        "home_flash_products" to mapOf(Language.UZ to "Chegirmadagi mahsulotlar", Language.RU to "Товары со скидкой"),
        "home_flash_old_price" to mapOf(Language.UZ to "eski narx", Language.RU to "старая цена"),
        "home_rating_suffix" to mapOf(Language.UZ to " baho", Language.RU to " оценки"),

        // ========== Addresses ==========
        "addresses_title" to mapOf(Language.UZ to "Manzillarim", Language.RU to "Мои адреса"),
        "addresses_empty" to mapOf(Language.UZ to "Manzillar hozircha yo'q", Language.RU to "Адресов пока нет"),
        "addresses_add" to mapOf(Language.UZ to "Yangi manzil qo'shish", Language.RU to "Добавить новый адрес"),
        "addresses_add_title" to mapOf(Language.UZ to "Yangi manzil", Language.RU to "Новый адрес"),
        "addresses_name_label" to mapOf(Language.UZ to "Manzil nomi", Language.RU to "Название адреса"),
        "addresses_address_label" to mapOf(Language.UZ to "Manzil", Language.RU to "Адрес"),
        "addresses_save" to mapOf(Language.UZ to "Saqlash", Language.RU to "Сохранить"),
        "addresses_delete" to mapOf(Language.UZ to "O'chirish", Language.RU to "Удалить"),
        "addresses_home" to mapOf(Language.UZ to "Uy", Language.RU to "Дом"),
        "addresses_office" to mapOf(Language.UZ to "Ish", Language.RU to "Офис"),
        "addresses_other" to mapOf(Language.UZ to "Boshqa", Language.RU to "Другое"),
        "addresses_edit" to mapOf(Language.UZ to "Tahrirlash", Language.RU to "Редактировать"),
        "addresses_set_default" to mapOf(Language.UZ to "Asosiy qilish", Language.RU to "Сделать основным"),
        "addresses_default" to mapOf(Language.UZ to "Asosiy", Language.RU to "Основной"),
        "addresses_served" to mapOf(Language.UZ to "Xizmat hududida", Language.RU to "В зоне обслуживания"),
        "addresses_not_served" to mapOf(Language.UZ to "Xizmat hududidan tashqarida", Language.RU to "Вне зоны обслуживания"),
        "addresses_region_label" to mapOf(Language.UZ to "Viloyat/Shahar", Language.RU to "Регион/Город"),
        "addresses_district_label" to mapOf(Language.UZ to "Tuman", Language.RU to "Район"),
        "addresses_line1_label" to mapOf(Language.UZ to "Ko'cha, uy raqami", Language.RU to "Улица, дом"),
        "addresses_line2_label" to mapOf(Language.UZ to "Qo'shimcha (mo'ljal)", Language.RU to "Дополнительно (ориентир)"),
        "addresses_postal_label" to mapOf(Language.UZ to "Pochta indeksi", Language.RU to "Почтовый индекс"),
        "addresses_phone_label" to mapOf(Language.UZ to "Telefon", Language.RU to "Телефон"),
        "addresses_is_default" to mapOf(Language.UZ to "Asosiy manzil", Language.RU to "Основной адрес"),
        "addresses_delete_confirm_title" to mapOf(Language.UZ to "Manzilni o'chirish", Language.RU to "Удалить адрес"),
        "addresses_delete_confirm_body" to mapOf(Language.UZ to "Bu manzilni o'chirishni istaysizmi?", Language.RU to "Вы уверены, что хотите удалить этот адрес?"),
        "addresses_cancel" to mapOf(Language.UZ to "Bekor qilish", Language.RU to "Отмена"),
        "address_search_hint" to mapOf(Language.UZ to "Manzil qidirish...", Language.RU to "Поиск адреса..."),
        "address_search_empty" to mapOf(Language.UZ to "Hech narsa topilmadi", Language.RU to "Ничего не найдено"),
        "address_picked_label" to mapOf(Language.UZ to "Tanlangan manzil", Language.RU to "Выбранный адрес"),
        "address_pick_on_map" to mapOf(Language.UZ to "Xaritadan tanlash", Language.RU to "Выбрать на карте"),
        "checkout_address_select" to mapOf(Language.UZ to "Saqlangan manzildan tanlang", Language.RU to "Выберите сохраненный адрес"),

        // ========== Payment methods ==========
        "payments_title" to mapOf(Language.UZ to "To'lov usullari", Language.RU to "Способы оплаты"),
        "payments_empty" to mapOf(Language.UZ to "Kartalar hozircha yo'q", Language.RU to "Карт пока нет"),
        "payments_add" to mapOf(Language.UZ to "Karta qo'shish", Language.RU to "Добавить карту"),
        "payments_add_title" to mapOf(Language.UZ to "Yangi karta", Language.RU to "Новая карта"),
        "payments_card_number" to mapOf(Language.UZ to "Karta raqami", Language.RU to "Номер карты"),
        "payments_card_holder" to mapOf(Language.UZ to "Karta egasi", Language.RU to "Владелец карты"),
        "payments_expiry" to mapOf(Language.UZ to "Amal qilish muddati", Language.RU to "Срок действия"),
        "payments_save" to mapOf(Language.UZ to "Saqlash", Language.RU to "Сохранить"),
        "payments_delete" to mapOf(Language.UZ to "O'chirish", Language.RU to "Удалить"),
        "payments_cash" to mapOf(Language.UZ to "Naqd pul", Language.RU to "Наличные"),
        "payments_card" to mapOf(Language.UZ to "Bank kartasi", Language.RU to "Банковская карта"),

        // ========== Settings ==========
        "settings_title" to mapOf(Language.UZ to "Sozlamalar", Language.RU to "Настройки"),
        "settings_language" to mapOf(Language.UZ to "Til", Language.RU to "Язык"),
        "settings_appearance" to mapOf(Language.UZ to "Ko'rinish", Language.RU to "Внешний вид"),
        "settings_notifications" to mapOf(Language.UZ to "Bildirishnomalar", Language.RU to "Уведомления"),
        "settings_notif_desc" to mapOf(Language.UZ to "Buyurtma holati haqida xabarlar", Language.RU to "Уведомления о статусе заказа"),
        "settings_about" to mapOf(Language.UZ to "Ilova haqida", Language.RU to "О приложении"),
        "settings_version" to mapOf(Language.UZ to "Versiya", Language.RU to "Версия"),
        "settings_enabled" to mapOf(Language.UZ to "Yoqilgan", Language.RU to "Включено"),
        "settings_disabled" to mapOf(Language.UZ to "O'chirilgan", Language.RU to "Выключено"),

        // ========== Help ==========
        "help_title" to mapOf(Language.UZ to "Yordam", Language.RU to "Помощь"),
        "help_faq" to mapOf(Language.UZ to "Ko'p so'raladigan savollar", Language.RU to "Частые вопросы"),
        "help_q1" to mapOf(Language.UZ to "Buyurtmani qanday berish mumkin?", Language.RU to "Как оформить заказ?"),
        "help_a1" to mapOf(Language.UZ to "Mahsulotni savatga qo'shing, keyin 'Buyurtma berish' tugmasini bosing va manzil hamda to'lov usulini tanlang.", Language.RU to "Добавьте товар в корзину, нажмите «Оформить заказ» и выберите адрес и способ оплаты."),
        "help_q2" to mapOf(Language.UZ to "Yetkazib berish qancha davom etadi?", Language.RU to "Сколько длится доставка?"),
        "help_a2" to mapOf(Language.UZ to "Toshkent shahrida 2-5 ish kuni ichida yetkaziladi.", Language.RU to "По Ташкенту доставка занимает 2-5 рабочих дней."),
        "help_q3" to mapOf(Language.UZ to "Buyurtmani qaytarish mumkinmi?", Language.RU to "Можно ли вернуть заказ?"),
        "help_a3" to mapOf(Language.UZ to "Ha, 30 kun ichida mahsulotni bepul qaytarish mumkin.", Language.RU to "Да, товар можно вернуть бесплатно в течение 30 дней."),
        "help_q4" to mapOf(Language.UZ to "To'lov qanday amalga oshiriladi?", Language.RU to "Как осуществляется оплата?"),
        "help_a4" to mapOf(Language.UZ to "Naqd pul, bank kartasi yoki yetkazilganda to'lash mumkin.", Language.RU to "Наличными, банковской картой или при получении."),
        "help_contact" to mapOf(Language.UZ to "Aloqa: +998 71 200 00 00", Language.RU to "Связь: +998 71 200 00 00"),

        // ========== Notifications ==========
        "notifications_title" to mapOf(Language.UZ to "Bildirishnomalar", Language.RU to "Уведомления"),
        "notifications_empty_title" to mapOf(Language.UZ to "Bildirishnomalar yo'q", Language.RU to "Нет уведомлений"),
        "notifications_empty_subtitle" to mapOf(Language.UZ to "Yangi xabarlar paydo bo'lganda ko'rasiz", Language.RU to "Вы увидите новые сообщения здесь"),
        "notifications_retry" to mapOf(Language.UZ to "Qayta urinish", Language.RU to "Повторить"),
        "notifications_mark_all" to mapOf(Language.UZ to "Hammasini o'qilgan deb belgilash", Language.RU to "Отметить все как прочитанные"),

        // ========== PlaceholderScreen ==========
        "placeholder_title" to mapOf(Language.UZ to "Tez kunda", Language.RU to "Скоро"),
        "placeholder_subtitle" to mapOf(Language.UZ to "Bu bo'lim hozircha ishlamaydi", Language.RU to "Этот раздел пока не работает"),

        // ========== ProductCard ==========
        "product_card_fragile" to mapOf(Language.UZ to "Ehtiyot", Language.RU to "Осторожно"),
        "product_card_default_brand" to mapOf(Language.UZ to "Mahsulot", Language.RU to "Товар"),
        "product_card_add_to_cart" to mapOf(Language.UZ to "Savatga", Language.RU to "В корзину"),
        "product_card_colors" to mapOf(Language.UZ to " rang", Language.RU to " цвета"),

        // ========== ReviewBottomSheet ==========
        "review_star_1" to mapOf(Language.UZ to "Yomon", Language.RU to "Плохо"),
        "review_star_2" to mapOf(Language.UZ to "Qoniqarsiz", Language.RU to "Неудовлетворительно"),
        "review_star_3" to mapOf(Language.UZ to "O'rtacha", Language.RU to "Средне"),
        "review_star_4" to mapOf(Language.UZ to "Yaxshi", Language.RU to "Хорошо"),
        "review_star_5" to mapOf(Language.UZ to "A'lo!", Language.RU to "Отлично!"),
        "review_title_update" to mapOf(Language.UZ to "Bahoni yangilash", Language.RU to "Обновить оценку"),
        "review_title_new" to mapOf(Language.UZ to "Baho berish", Language.RU to "Оценить"),
        "review_star_hint" to mapOf(Language.UZ to "Yulduz tanlang", Language.RU to "Выберите звезду"),
        "review_placeholder" to mapOf(Language.UZ to "Mahsulot haqida fikringizni yozing...", Language.RU to "Напишите отзыв о товаре..."),
        "map_picker_title" to mapOf(Language.UZ to "Xaritadan tanlash", Language.RU to "Выбрать на карте"),
        "map_picker_hint" to mapOf(Language.UZ to "Xaritada joyni bosing", Language.RU to "Нажмите на место на карте"),
        "map_picker_confirm" to mapOf(Language.UZ to "Tasdiqlash", Language.RU to "Подтвердить"),
        "map_picker_loading_zones" to mapOf(Language.UZ to "Xizmat hududlari yuklanmoqda...", Language.RU to "Загрузка зон обслуживания..."),
        "map_picker_outside" to mapOf(Language.UZ to "Bu nuqta xizmat hududidan tashqarida — binafsha hudud ichidan tanlang", Language.RU to "Точка вне зоны обслуживания — выберите внутри фиолетовой зоны"),

        "review_cancel" to mapOf(Language.UZ to "Bekor qilish", Language.RU to "Отмена"),
        "review_update" to mapOf(Language.UZ to "Yangilash", Language.RU to "Обновить"),
        "review_submit" to mapOf(Language.UZ to "Yuborish", Language.RU to "Отправить"),

        "forgot_title" to mapOf(Language.UZ to "Parolni tiklash", Language.RU to "Восстановление пароля"),
        "forgot_desc" to mapOf(Language.UZ to "Emailingizni kiriting — tiklash kodini yuboramiz", Language.RU to "Введите email — отправим код восстановления"),
        "forgot_code_title" to mapOf(Language.UZ to "Kodni kiriting", Language.RU to "Введите код"),
        "forgot_code_desc" to mapOf(Language.UZ to "Emailingizga yuborilgan 6 xonali kodni kiriting", Language.RU to "Введите 6-значный код, отправленный на email"),
        "forgot_new_pass_title" to mapOf(Language.UZ to "Yangi parol", Language.RU to "Новый пароль"),
        "forgot_new_desc" to mapOf(Language.UZ to "Yangi parolingizni kiriting", Language.RU to "Введите новый пароль"),
        "forgot_send_code" to mapOf(Language.UZ to "Kod yuborish", Language.RU to "Отправить код"),
        "forgot_code_label" to mapOf(Language.UZ to "Tasdiqlash kodi", Language.RU to "Код подтверждения"),
        "forgot_verify" to mapOf(Language.UZ to "Tasdiqlash", Language.RU to "Подтвердить"),
        "forgot_resend" to mapOf(Language.UZ to "Kodni qayta yuborish", Language.RU to "Отправить код повторно"),
        "forgot_new_pass" to mapOf(Language.UZ to "Yangi parol", Language.RU to "Новый пароль"),
        "forgot_save" to mapOf(Language.UZ to "Saqlash", Language.RU to "Сохранить"),
    )

    fun get(key: String, language: Language): String {
        return strings[key]?.get(language) ?: key
    }
}

/** Narxni nuqtasiz formatlaydi: 120.99 → "120", 150.50 → "150" */
fun formatPrice(value: Double?): String {
    if (value == null) return "0"
    return kotlin.math.floor(value).toLong().toString()
}
